version: '3.7'

services:

  sample-prod:
    container_name: sample-prod
    image: dm1st/eatsy-react-ui-docker:latest
    build:
      context: .
      dockerfile: dockerfile.prod
    ports:
      - '1337:80'